KeyDef(None, "No Key")

KeyDef(GraveAccent, "Grave Accent")
KeyDef(0, "0")
KeyDef(1, "1")
KeyDef(2, "2")
KeyDef(3, "3")
KeyDef(4, "4")
KeyDef(5, "5")
KeyDef(6, "6")
KeyDef(7, "7")
KeyDef(8, "8")
KeyDef(9, "9")
KeyDef(Minus, "Minus")
KeyDef(Equal, "Equal")
KeyDef(Backspace, "Backspace")
KeyDef(A, "A")
KeyDef(B, "B")
KeyDef(C, "C")
KeyDef(D, "D")
KeyDef(E, "E")
KeyDef(F, "F")
KeyDef(G, "G")
KeyDef(H, "H")
KeyDef(I, "I")
KeyDef(J, "J")
KeyDef(K, "K")
KeyDef(L, "L")
KeyDef(M, "M")
KeyDef(N, "N")
KeyDef(O, "O")
KeyDef(P, "P")
KeyDef(Q, "Q")
KeyDef(R, "R")
KeyDef(S, "S")
KeyDef(T, "T")
KeyDef(U, "U")
KeyDef(V, "V")
KeyDef(W, "W")
KeyDef(X, "X")
KeyDef(Y, "Y")
KeyDef(Z, "Z")
KeyDef(Space, "Space")
KeyDef(Period, "Period")
KeyDef(ForwardSlash, "Forward Slash")
KeyDef(Comma, "Comma")
KeyDef(Quote, "Quote")
KeyDef(LeftBracket, "Left Bracket")
KeyDef(RightBracket, "Right Bracket")
KeyDef(PRINTABLE_END, "ERROR - invalid key")

KeyDef(Tab, "Tab") // TODO(tbt): this is a hack to stop text edits consuming tab key presses
KeyDef(F1, "F1")
KeyDef(F2, "F2")
KeyDef(F3, "F3")
KeyDef(F4, "F4")
KeyDef(F5, "F5")
KeyDef(F6, "F6")
KeyDef(F7, "F7")
KeyDef(F8, "F8")
KeyDef(F9, "F9")
KeyDef(F10, "F10")
KeyDef(F11, "F11")
KeyDef(F12, "F12")
KeyDef(Delete, "Delete")
KeyDef(Insert, "Insert")
KeyDef(Esc, "Escape")
KeyDef(Enter, "Enter")
KeyDef(Up, "Up")
KeyDef(Left, "Left")
KeyDef(Down, "Down")
KeyDef(Right, "Right")
KeyDef(PageUp, "Page Up")
KeyDef(PageDown, "Page Down")
KeyDef(Home, "Home")
KeyDef(End, "End")
KeyDef(Colon, "Colon")

KeyDef(MODIFIER_BEGIN, "ERROR - invalid key")
KeyDef(Ctrl, "Ctrl")
KeyDef(Shift, "Shift")
KeyDef(Alt, "Alt")
KeyDef(MODIFIER_END, "ERROR - invalid key")

KeyDef(MOUSE_BEGIN, "ERROR - invalid key")
KeyDef(MouseButtonLeft, "Left Mouse Button")
KeyDef(MouseButtonMiddle, "Middle Mouse Button")
KeyDef(MouseButtonRight, "Right Mouse Button")
KeyDef(MouseButtonForward, "Forward Mouse Button")
KeyDef(MouseButtonBackward, "Backward Mouse Button")
KeyDef(MOUSE_END, "ERROR - invalid key")

KeyDef(MAX, "ERROR - invalid key")

#undef KeyDef
